variables:
    PLATFORM: $BASENAME-$REVISION

packages:
  - name: goldstone-platform-config-$PLATFORM
    arch: $ARCH
    version: 1.0.0
    copyright: Copyright 2020 Wataru Ishida
    maintainer: wataru.ishid@gmail.com
    changelog: Initial
    support:   wataru.ishid@gmail.com
    summary: Goldstone config file for $PLATFORM
    files:
        builds/sai.profile: /var/lib/goldstone/device/$PLATFORM/usonic/sai.profile
        builds/config.bcm: /var/lib/goldstone/device/$PLATFORM/usonic/config.bcm
        builds/port_config.ini: /var/lib/goldstone/device/$PLATFORM/usonic/port_config.ini
        builds/blacklist.conf: /etc/modprobe.d/$PLATFORM.conf
